package entity;
// Generated Mar 9, 2019 2:17:56 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AerialPlans generated by hbm2java
 */
@Entity
@Table(name = "aerial_plans", catalog = "drone")
public class AerialPlans implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9188545556912901379L;
	private Integer aerialPlanId;
	private Projects projects;
	private String usage;
	private String area;
	private Date aerialPlanStartDate;
	private Date aerialPlanEndDate;
	private Integer amslFrom;
	private Integer amslTo;
	private Integer agl;
	private String takeOffLocationName;
	private Integer takeOffNDegree;
	private Integer takeOffNMinute;
	private Float takeOffNSecond;
	private Integer takeOffEDegree;
	private Integer takeOffEMinute;
	private Float takeOffESecond;
	private Integer areaCenterNDegree;
	private Integer areaCenterNMinute;
	private Float areaCenterNSecond;
	private Integer areaCenterEDegree;
	private Integer areaCenterEMinute;
	private Float areaCenterESecond;
	private Integer operationDiameter;
	private Set<AerialActivities> aerialActivitieses = new HashSet<AerialActivities>(0);
	private Set<Areas> areases = new HashSet<Areas>(0);
	private Set<OperationlimitsAerialplans> operationlimitsAerialplanses = new HashSet<OperationlimitsAerialplans>(0);
	private Set<Missions> missionses = new HashSet<Missions>(0);
	
	private AerialPlanFlow aerialPlanFlow;
	
	@Embedded
	public AerialPlanFlow getAerialPlanFlow() {
		return aerialPlanFlow;
	}

	public void setAerialPlanFlow(AerialPlanFlow aerialPlanFlow) {
		this.aerialPlanFlow = aerialPlanFlow;
	}

	public AerialPlans() {
	}

	public AerialPlans(Integer aerialPlanId, Projects projects, String usage, String area, Date aerialPlanStartDate,
			Date aerialPlanEndDate, Integer amslFrom, Integer amslTo, Integer agl, String takeOffLocationName,
			Integer takeOffNDegree, Integer takeOffNMinute, Float takeOffNSecond, Integer takeOffEDegree,
			Integer takeOffEMinute, Float takeOffESecond, Integer areaCenterNDegree, Integer areaCenterNMinute,
			Float areaCenterNSecond, Integer areaCenterEDegree, Integer areaCenterEMinute, Float areaCenterESecond,
			Integer operationDiameter, Set<AerialActivities> aerialActivitieses, Set<Areas> areases,
			Set<OperationlimitsAerialplans> operationlimitsAerialplanses, Set<Missions> missionses,
			AerialPlanFlow aerialPlanFlow) {
		super();
		this.aerialPlanId = aerialPlanId;
		this.projects = projects;
		this.usage = usage;
		this.area = area;
		this.aerialPlanStartDate = aerialPlanStartDate;
		this.aerialPlanEndDate = aerialPlanEndDate;
		this.amslFrom = amslFrom;
		this.amslTo = amslTo;
		this.agl = agl;
		this.takeOffLocationName = takeOffLocationName;
		this.takeOffNDegree = takeOffNDegree;
		this.takeOffNMinute = takeOffNMinute;
		this.takeOffNSecond = takeOffNSecond;
		this.takeOffEDegree = takeOffEDegree;
		this.takeOffEMinute = takeOffEMinute;
		this.takeOffESecond = takeOffESecond;
		this.areaCenterNDegree = areaCenterNDegree;
		this.areaCenterNMinute = areaCenterNMinute;
		this.areaCenterNSecond = areaCenterNSecond;
		this.areaCenterEDegree = areaCenterEDegree;
		this.areaCenterEMinute = areaCenterEMinute;
		this.areaCenterESecond = areaCenterESecond;
		this.operationDiameter = operationDiameter;
		this.aerialActivitieses = aerialActivitieses;
		this.areases = areases;
		this.operationlimitsAerialplanses = operationlimitsAerialplanses;
		this.missionses = missionses;
		this.aerialPlanFlow = aerialPlanFlow;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Aerial_Plan_ID", unique = true, nullable = false)
	public Integer getAerialPlanId() {
		return this.aerialPlanId;
	}

	public void setAerialPlanId(Integer aerialPlanId) {
		this.aerialPlanId = aerialPlanId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Project_ID")
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@Column(name = "Usefor", length = 50)
	public String getUsage() {
		return this.usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	@Column(name = "Area", length = 50)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Start_Date", length = 10)
	public Date getAerialPlanStartDate() {
		return aerialPlanStartDate;
	}

	public void setAerialPlanStartDate(Date aerialPlanStartDate) {
		this.aerialPlanStartDate = aerialPlanStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "End_Date", length = 10)
	public Date getAerialPlanEndDate() {
		return aerialPlanEndDate;
	}

	public void setAerialPlanEndDate(Date aerialPlanEndDate) {
		this.aerialPlanEndDate = aerialPlanEndDate;
	}
	
	@Column(name = "AMSL_From")
	public Integer getAmslFrom() {
		return this.amslFrom;
	}

	public void setAmslFrom(Integer amslFrom) {
		this.amslFrom = amslFrom;
	}

	@Column(name = "AMSL_To")
	public Integer getAmslTo() {
		return this.amslTo;
	}

	public void setAmslTo(Integer amslTo) {
		this.amslTo = amslTo;
	}

	@Column(name = "AGL")
	public Integer getAgl() {
		return this.agl;
	}

	public void setAgl(Integer agl) {
		this.agl = agl;
	}

	@Column(name = "Take_Off_Location_Name", length = 50)
	public String getTakeOffLocationName() {
		return this.takeOffLocationName;
	}

	public void setTakeOffLocationName(String takeOffLocationName) {
		this.takeOffLocationName = takeOffLocationName;
	}

	@Column(name = "Take_Off_N_Degree")
	public Integer getTakeOffNDegree() {
		return this.takeOffNDegree;
	}

	public void setTakeOffNDegree(Integer takeOffNDegree) {
		this.takeOffNDegree = takeOffNDegree;
	}

	@Column(name = "Take_Off_N_Minute")
	public Integer getTakeOffNMinute() {
		return this.takeOffNMinute;
	}

	public void setTakeOffNMinute(Integer takeOffNMinute) {
		this.takeOffNMinute = takeOffNMinute;
	}

	@Column(name = "Take_Off_N_Second", precision = 2)
	public Float getTakeOffNSecond() {
		return this.takeOffNSecond;
	}

	public void setTakeOffNSecond(Float takeOffNSecond) {
		this.takeOffNSecond = takeOffNSecond;
	}

	@Column(name = "Take_Off_E_Degree")
	public Integer getTakeOffEDegree() {
		return this.takeOffEDegree;
	}

	public void setTakeOffEDegree(Integer takeOffEDegree) {
		this.takeOffEDegree = takeOffEDegree;
	}

	@Column(name = "Take_Off_E_Minute")
	public Integer getTakeOffEMinute() {
		return this.takeOffEMinute;
	}

	public void setTakeOffEMinute(Integer takeOffEMinute) {
		this.takeOffEMinute = takeOffEMinute;
	}

	@Column(name = "Take_Off_E_Second", precision = 2)
	public Float getTakeOffESecond() {
		return this.takeOffESecond;
	}

	public void setTakeOffESecond(Float takeOffESecond) {
		this.takeOffESecond = takeOffESecond;
	}

	@Column(name = "Area_Center_N_Degree")
	public Integer getAreaCenterNDegree() {
		return this.areaCenterNDegree;
	}

	public void setAreaCenterNDegree(Integer areaCenterNDegree) {
		this.areaCenterNDegree = areaCenterNDegree;
	}

	@Column(name = "Area_Center_N_Minute")
	public Integer getAreaCenterNMinute() {
		return this.areaCenterNMinute;
	}

	public void setAreaCenterNMinute(Integer areaCenterNMinute) {
		this.areaCenterNMinute = areaCenterNMinute;
	}

	@Column(name = "Area_Center_N_Second", precision = 2)
	public Float getAreaCenterNSecond() {
		return this.areaCenterNSecond;
	}

	public void setAreaCenterNSecond(Float areaCenterNSecond) {
		this.areaCenterNSecond = areaCenterNSecond;
	}

	@Column(name = "Area_Center_E_Degree")
	public Integer getAreaCenterEDegree() {
		return this.areaCenterEDegree;
	}

	public void setAreaCenterEDegree(Integer areaCenterEDegree) {
		this.areaCenterEDegree = areaCenterEDegree;
	}

	@Column(name = "Area_Center_E_Minute")
	public Integer getAreaCenterEMinute() {
		return this.areaCenterEMinute;
	}

	public void setAreaCenterEMinute(Integer areaCenterEMinute) {
		this.areaCenterEMinute = areaCenterEMinute;
	}

	@Column(name = "Area_Center_E_Second", precision = 2)
	public Float getAreaCenterESecond() {
		return this.areaCenterESecond;
	}

	public void setAreaCenterESecond(Float areaCenterESecond) {
		this.areaCenterESecond = areaCenterESecond;
	}

	@Column(name = "Operation_Diameter")
	public Integer getOperationDiameter() {
		return this.operationDiameter;
	}

	public void setOperationDiameter(Integer operationDiameter) {
		this.operationDiameter = operationDiameter;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aerialPlans")
	public Set<AerialActivities> getAerialActivitieses() {
		return this.aerialActivitieses;
	}

	public void setAerialActivitieses(Set<AerialActivities> aerialActivitieses) {
		this.aerialActivitieses = aerialActivitieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aerialPlans")
	public Set<Areas> getAreases() {
		return this.areases;
	}

	public void setAreases(Set<Areas> areases) {
		this.areases = areases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aerialPlans")
	public Set<OperationlimitsAerialplans> getOperationlimitsAerialplanses() {
		return this.operationlimitsAerialplanses;
	}

	public void setOperationlimitsAerialplanses(Set<OperationlimitsAerialplans> operationlimitsAerialplanses) {
		this.operationlimitsAerialplanses = operationlimitsAerialplanses;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aerialPlans")
	public Set<Missions> getMissionses() {
		return this.missionses;
	}

	public void setMissionses(Set<Missions> missionses) {
		this.missionses = missionses;
	}

}
