package entity;
// Generated Mar 9, 2019 2:17:56 AM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AerialActivities generated by hbm2java
 */
@Entity
@Table(name = "aerial_activities", catalog = "drone")
public class AerialActivities implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4081980226262103220L;
	private int aerialActivityId;
	private AerialPlans aerialPlans;
	private byte[] areaFile;
	private Date startTime;
	private Date endTime;

	public AerialActivities() {
	}

	public AerialActivities(int aerialActivityId) {
		this.aerialActivityId = aerialActivityId;
	}

	public AerialActivities(int aerialActivityId, AerialPlans aerialPlans, byte[] areaFile, Date startTime,
			Date endTime) {
		this.aerialActivityId = aerialActivityId;
		this.aerialPlans = aerialPlans;
		this.areaFile = areaFile;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Aerial_Activity_ID", unique = true, nullable = false)
	public int getAerialActivityId() {
		return this.aerialActivityId;
	}

	public void setAerialActivityId(int aerialActivityId) {
		this.aerialActivityId = aerialActivityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Aerial_Plan_ID")
	public AerialPlans getAerialPlans() {
		return this.aerialPlans;
	}

	public void setAerialPlans(AerialPlans aerialPlans) {
		this.aerialPlans = aerialPlans;
	}

	@Column(name = "Area_File")
	public byte[] getAreaFile() {
		return this.areaFile;
	}

	public void setAreaFile(byte[] areaFile) {
		this.areaFile = areaFile;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Start_Time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "End_Time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
