package entity;
// Generated Mar 9, 2019 2:17:56 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Areas generated by hbm2java
 */
@Entity
@Table(name = "areas", catalog = "drone")
public class Areas implements java.io.Serializable {

	private Integer areaId;
	private AerialPlans aerialPlans;
	private Integer pointSeq;
	private Integer NDegree;
	private Integer NMinute;
	private Float NSecond;
	private Integer EDegree;
	private Integer EMinute;
	private Float ESecond;

	public Areas() {
	}

	public Areas(AerialPlans aerialPlans, Integer pointSeq, Integer NDegree, Integer NMinute, Float NSecond,
			Integer EDegree, Integer EMinute, Float ESecond) {
		this.aerialPlans = aerialPlans;
		this.pointSeq = pointSeq;
		this.NDegree = NDegree;
		this.NMinute = NMinute;
		this.NSecond = NSecond;
		this.EDegree = EDegree;
		this.EMinute = EMinute;
		this.ESecond = ESecond;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Area_ID", unique = true, nullable = false)
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Aerial_Plan_ID")
	public AerialPlans getAerialPlans() {
		return this.aerialPlans;
	}

	public void setAerialPlans(AerialPlans aerialPlans) {
		this.aerialPlans = aerialPlans;
	}

	@Column(name = "Point_Seq")
	public Integer getPointSeq() {
		return this.pointSeq;
	}

	public void setPointSeq(Integer pointSeq) {
		this.pointSeq = pointSeq;
	}

	@Column(name = "N_Degree")
	public Integer getNDegree() {
		return this.NDegree;
	}

	public void setNDegree(Integer NDegree) {
		this.NDegree = NDegree;
	}

	@Column(name = "N_Minute")
	public Integer getNMinute() {
		return this.NMinute;
	}

	public void setNMinute(Integer NMinute) {
		this.NMinute = NMinute;
	}

	@Column(name = "N_Second", precision = 2)
	public Float getNSecond() {
		return this.NSecond;
	}

	public void setNSecond(Float NSecond) {
		this.NSecond = NSecond;
	}

	@Column(name = "E_Degree")
	public Integer getEDegree() {
		return this.EDegree;
	}

	public void setEDegree(Integer EDegree) {
		this.EDegree = EDegree;
	}

	@Column(name = "E_Minute")
	public Integer getEMinute() {
		return this.EMinute;
	}

	public void setEMinute(Integer EMinute) {
		this.EMinute = EMinute;
	}

	@Column(name = "E_Second", precision = 2)
	public Float getESecond() {
		return this.ESecond;
	}

	public void setESecond(Float ESecond) {
		this.ESecond = ESecond;
	}

}
