package entity;
// Generated 2019/5/19 ?? 06:30:15 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Code generated by hbm2java
 */
@Entity
@Table(name = "code")
public class Code implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3456293821850312533L;
	private Integer codeId;
	private Integer nodeId;
	private String codeType;
	private String code;
	private String codeContent;
	private Integer parentNodeId;

	public Code() {
	}

	public Code(Integer nodeId, String codeType, String code, String codeContent, Integer parentNodeId) {
		this.nodeId = nodeId;
		this.codeType = codeType;
		this.code = code;
		this.codeContent = codeContent;
		this.parentNodeId = parentNodeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Code_ID", unique = true, nullable = false)
	public Integer getCodeId() {
		return this.codeId;
	}

	public void setCodeId(Integer codeId) {
		this.codeId = codeId;
	}

	@Column(name = "Node_ID")
	public Integer getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(Integer nodeId) {
		this.nodeId = nodeId;
	}

	@Column(name = "Code_Type", length = 30)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "Code", length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "Code_Content", length = 100)
	public String getCodeContent() {
		return this.codeContent;
	}

	public void setCodeContent(String codeContent) {
		this.codeContent = codeContent;
	}

	@Column(name = "Parent_Node_ID")
	public Integer getParentNodeId() {
		return this.parentNodeId;
	}

	public void setParentNodeId(Integer parentNodeId) {
		this.parentNodeId = parentNodeId;
	}

}
