package entity;
// Generated Mar 9, 2019 2:17:56 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Functions generated by hbm2java
 */
@Entity
@Table(name = "functions", catalog = "drone")
public class Functions implements java.io.Serializable {

	private Integer functionId;
	private String functionName;
	private Set rolesFunctionses = new HashSet(0);

	public Functions() {
	}

	public Functions(String functionName, Set rolesFunctionses) {
		this.functionName = functionName;
		this.rolesFunctionses = rolesFunctionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Function_ID", unique = true, nullable = false)
	public Integer getFunctionId() {
		return this.functionId;
	}

	public void setFunctionId(Integer functionId) {
		this.functionId = functionId;
	}

	@Column(name = "Function_Name", length = 50)
	public String getFunctionName() {
		return this.functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "functions")
	public Set getRolesFunctionses() {
		return this.rolesFunctionses;
	}

	public void setRolesFunctionses(Set rolesFunctionses) {
		this.rolesFunctionses = rolesFunctionses;
	}

}
