package entity;

// default package
// Generated Mar 23, 2019 3:15:02 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModificationDetail generated by hbm2java
 */
@Entity
@Table(name = "modification_detail", catalog = "drone")
public class ModificationDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2623407360118891264L;
	private Integer modificationDetailId;
	private Modifications modifications;
	private int seq;
	private Integer detailType;
	private String status;
	private String comment;
	private String modificationPhoto;

	public ModificationDetail() {
	}

	public ModificationDetail(Modifications modifications, int seq) {
		this.modifications = modifications;
		this.seq = seq;
	}

	public ModificationDetail(int seq, Integer detailType, String status, String comment, String modificationPhoto) {
		super();
		this.seq = seq;
		this.detailType = detailType;
		this.status = status;
		this.comment = comment;
		this.modificationPhoto = modificationPhoto;
	}

	public ModificationDetail(Modifications modifications, int seq, Integer detailType, String status, String comment,
			String modificationPhoto) {
		this.modifications = modifications;
		this.seq = seq;
		this.detailType = detailType;
		this.status = status;
		this.comment = comment;
		this.modificationPhoto = modificationPhoto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Modification_Detail_ID", unique = true, nullable = false)
	public Integer getModificationDetailId() {
		return this.modificationDetailId;
	}

	public void setModificationDetailId(Integer modificationDetailId) {
		this.modificationDetailId = modificationDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Modification_ID", nullable = false)
	public Modifications getModifications() {
		return this.modifications;
	}

	public void setModifications(Modifications modifications) {
		this.modifications = modifications;
	}

	@Column(name = "Seq", nullable = false)
	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	@Column(name = "Detail_Type")
	public Integer getDetailType() {
		return this.detailType;
	}

	public void setDetailType(Integer detailType) {
		this.detailType = detailType;
	}

	@Column(name = "Status", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Comment", length = 50)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "Modification_Photo")
	public String getModificationPhoto() {
		return modificationPhoto;
	}

	public void setModificationPhoto(String modificationPhoto) {
		this.modificationPhoto = modificationPhoto;
	}

}
