package entity;

// default package
// Generated Mar 23, 2019 3:15:02 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Modifications generated by hbm2java
 */
@Entity
@Table(name = "modifications", catalog = "drone")
public class Modifications implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8297798838816303031L;
	private Integer modificationId;
	private Equipments equipments;
	private Date modificationDate;
	private String modificationPerson;
	private Set<ModificationDetail> modificationDetails = new HashSet<ModificationDetail>(0);

	public Modifications() {
	}

	public Modifications(Equipments equipments, Date modificationDate, String modificationPerson,
			Set<ModificationDetail> modificationDetails) {
		this.equipments = equipments;
		this.modificationDate = modificationDate;
		this.modificationPerson = modificationPerson;
		this.modificationDetails = modificationDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Modification_ID", unique = true, nullable = false)
	public Integer getModificationId() {
		return this.modificationId;
	}

	public void setModificationId(Integer modificationId) {
		this.modificationId = modificationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Equipment_ID")
	public Equipments getEquipments() {
		return this.equipments;
	}

	public void setEquipments(Equipments equipments) {
		this.equipments = equipments;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Modification_Date", length = 10)
	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	@Column(name = "Modification_Person", length = 20)
	public String getModificationPerson() {
		return this.modificationPerson;
	}

	public void setModificationPerson(String modificationPerson) {
		this.modificationPerson = modificationPerson;
	}

	@OneToMany(fetch = FetchType.LAZY,cascade=CascadeType.ALL, mappedBy = "modifications")
	public Set<ModificationDetail> getModificationDetails() {
		return this.modificationDetails;
	}

	public void setModificationDetails(Set<ModificationDetail> modificationDetails) {
		this.modificationDetails = modificationDetails;
	}

}
