package entity;
// Generated Mar 9, 2019 2:17:56 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OperationlimitsLicenses generated by hbm2java
 */
@Entity
@Table(name = "operationlimits_licenses")
public class OperationlimitsLicenses implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3286537039865489007L;
	private int operationLimitsLicensesId;
	private Licenses licenses;
	private OperationLimits operationLimits;

	public OperationlimitsLicenses() {
	}

	public OperationlimitsLicenses(int operationLimitsLicensesId) {
		this.operationLimitsLicensesId = operationLimitsLicensesId;
	}

	public OperationlimitsLicenses(int operationLimitsLicensesId, Licenses licenses, OperationLimits operationLimits) {
		this.operationLimitsLicensesId = operationLimitsLicensesId;
		this.licenses = licenses;
		this.operationLimits = operationLimits;
	}

	@Id

	@Column(name = "OperationLimits_Licenses_ID", unique = true, nullable = false)
	public int getOperationLimitsLicensesId() {
		return this.operationLimitsLicensesId;
	}

	public void setOperationLimitsLicensesId(int operationLimitsLicensesId) {
		this.operationLimitsLicensesId = operationLimitsLicensesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "License_ID")
	public Licenses getLicenses() {
		return this.licenses;
	}

	public void setLicenses(Licenses licenses) {
		this.licenses = licenses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Operation_Limit_ID")
	public OperationLimits getOperationLimits() {
		return this.operationLimits;
	}

	public void setOperationLimits(OperationLimits operationLimits) {
		this.operationLimits = operationLimits;
	}

}
