package entity;

// default package
// Generated Mar 21, 2019 12:09:06 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Participations generated by hbm2java
 */
@Entity
@Table(name = "participations", catalog = "drone")
public class Participations implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5202927650060869567L;
	private Integer participationId;
	private Events events;
	private Persons persons;
	private byte[] photo;
	
	private ParticipationFlow participationFlow;
	
	
	@Embedded
	public ParticipationFlow getParticipationFlow() {
		return participationFlow;
	}

	public void setParticipationFlow(ParticipationFlow participationFlow) {
		this.participationFlow = participationFlow;
	}

	public Participations() {
	}

	

	public Participations(Events events, Persons persons, byte[] photo) {
		this.events = events;
		this.persons = persons;
		this.photo = photo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Participation_ID", unique = true, nullable = false)
	public Integer getParticipationId() {
		return this.participationId;
	}

	public void setParticipationId(Integer participationId) {
		this.participationId = participationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Event_ID")
	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Person_ID")
	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

	@Column(name = "Photo")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

}
