package entity;

// default package
// Generated Mar 21, 2019 12:09:06 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonsLicenses generated by hbm2java
 */
@Entity
@Table(name = "persons_licenses", catalog = "drone")
public class PersonsLicenses implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3153673597274013289L;
	private Integer personsLicensesId;
	private Licenses licenses;
	private Persons persons;
	private Date gotDate;
	private byte[] photo;
	
	private PersonsLicensesFlow personsLicensesFlow;
	
	
	@Embedded
	public PersonsLicensesFlow getPersonsLicensesFlow() {
		return personsLicensesFlow;
	}

	public void setPersonsLicensesFlow(PersonsLicensesFlow personsLicensesFlow) {
		this.personsLicensesFlow = personsLicensesFlow;
	}

	public PersonsLicenses() {
	}

	

	public PersonsLicenses(Licenses licenses, Persons persons) {
		this.licenses = licenses;
		this.persons = persons;
	}

	public PersonsLicenses(Licenses licenses, Persons persons, Date gotDate, byte[] photo) {
		this.licenses = licenses;
		this.persons = persons;
		this.gotDate = gotDate;
		this.photo = photo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Persons_Licenses_ID", unique = true, nullable = false)
	public Integer getPersonsLicensesId() {
		return this.personsLicensesId;
	}

	public void setPersonsLicensesId(Integer personsLicensesId) {
		this.personsLicensesId = personsLicensesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "License_ID", nullable = false)
	public Licenses getLicenses() {
		return this.licenses;
	}

	public void setLicenses(Licenses licenses) {
		this.licenses = licenses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Person_ID", nullable = false)
	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Got_Date", length = 10)
	public Date getGotDate() {
		return this.gotDate;
	}

	public void setGotDate(Date gotDate) {
		this.gotDate = gotDate;
	}

	@Column(name = "Photo")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

}
