package entity;
// Generated Mar 9, 2019 2:17:56 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonsAerialplans generated by hbm2java
 */
@Entity
@Table(name = "persons_aerialplans", catalog = "drone")
public class PersonsAerialplans implements java.io.Serializable {

	private Integer personsAerialPlansId;
	private AerialPlans aerialPlans;
	private Integer personId;

	public PersonsAerialplans() {
	}

	public PersonsAerialplans(AerialPlans aerialPlans, Integer personId) {
		this.aerialPlans = aerialPlans;
		this.personId = personId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Persons_AerialPlans_ID", unique = true, nullable = false)
	public Integer getPersonsAerialPlansId() {
		return this.personsAerialPlansId;
	}

	public void setPersonsAerialPlansId(Integer personsAerialPlansId) {
		this.personsAerialPlansId = personsAerialPlansId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Aerial_Plan_ID")
	public AerialPlans getAerialPlans() {
		return this.aerialPlans;
	}

	public void setAerialPlans(AerialPlans aerialPlans) {
		this.aerialPlans = aerialPlans;
	}

	@Column(name = "Person_ID")
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

}
