package entity;

// default package
// Generated 2019/6/24 ?? 12:30:56 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RealMissions generated by hbm2java
 */
@Entity
@Table(name = "real_missions", catalog = "drone")
public class RealMissions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6483648345358683013L;
	private Integer realMissionId;
	private AerialActivities aerialActivities;
	private Equipments equipments;
	private Persons persons;

	public RealMissions() {
	}

	public RealMissions(AerialActivities aerialActivities, Equipments equipments, Persons persons) {
		this.aerialActivities = aerialActivities;
		this.equipments = equipments;
		this.persons = persons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Real_Mission_ID", unique = true, nullable = false)
	public Integer getRealMissionId() {
		return this.realMissionId;
	}

	public void setRealMissionId(Integer realMissionId) {
		this.realMissionId = realMissionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Aerial_Activity_ID")
	public AerialActivities getAerialActivities() {
		return this.aerialActivities;
	}

	public void setAerialActivities(AerialActivities aerialActivities) {
		this.aerialActivities = aerialActivities;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Equipment_ID")
	public Equipments getEquipments() {
		return this.equipments;
	}

	public void setEquipments(Equipments equipments) {
		this.equipments = equipments;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Person_ID")
	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

}
