package entity;
// Generated Mar 9, 2019 2:17:56 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Registrations generated by hbm2java
 */
@Entity
@Table(name = "registrations", catalog = "drone")
public class Registrations implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9021654224043628415L;
	private Integer registrationId;
	private Equipments equipments;
	private String provider;
	private byte[] constructionData;
	private byte[] physicalData;
	private byte[] qrCode;
	private Date receivedDate;

	public Registrations() {
	}

	public Registrations(Equipments equipments) {
		this.equipments = equipments;
	}

	public Registrations(Equipments equipments, String provider, byte[] constructionData, byte[] physicalData,
			byte[] qrCode, Date receivedDate) {
		this.equipments = equipments;
		this.provider = provider;
		this.constructionData = constructionData;
		this.physicalData = physicalData;
		this.qrCode = qrCode;
		this.receivedDate = receivedDate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "equipments"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "Registration_ID", unique = true, nullable = false)
	public Integer getRegistrationId() {
		return this.registrationId;
	}

	public void setRegistrationId(Integer registrationId) {
		this.registrationId = registrationId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Equipments getEquipments() {
		return this.equipments;
	}

	public void setEquipments(Equipments equipments) {
		this.equipments = equipments;
	}

	@Column(name = "Provider", length = 64)
	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	@Column(name = "Construction_Data")
	public byte[] getConstructionData() {
		return this.constructionData;
	}

	public void setConstructionData(byte[] constructionData) {
		this.constructionData = constructionData;
	}

	@Column(name = "Physical_Data")
	public byte[] getPhysicalData() {
		return this.physicalData;
	}

	public void setPhysicalData(byte[] physicalData) {
		this.physicalData = physicalData;
	}

	@Column(name = "QR_Code")
	public byte[] getQrCode() {
		return this.qrCode;
	}

	public void setQrCode(byte[] qrCode) {
		this.qrCode = qrCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Received_Date", length = 19)
	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

}
