package entity;
// default package
// Generated Dec 7, 2020 9:02:24 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resources generated by hbm2java
 */
@Entity
@Table(name = "resources")
public class Resources implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8252578116444774739L;
	private Integer resourceId;
	private String resourceName;
	private String entryPoint;
	private String type;
	private Set<Permissions> permissionses = new HashSet<Permissions>(0);

	public Resources() {
	}

	public Resources(String resourceName, String entryPoint, String type, Set<Permissions> permissionses) {
		this.resourceName = resourceName;
		this.entryPoint = entryPoint;
		this.type = type;
		this.permissionses = permissionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Resource_ID", unique = true, nullable = false)
	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "Resource_Name", length = 50)
	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	@Column(name = "Entry_Point", length = 50)
	public String getEntryPoint() {
		return this.entryPoint;
	}

	public void setEntryPoint(String entryPoint) {
		this.entryPoint = entryPoint;
	}

	@Column(name = "Type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY,cascade=CascadeType.ALL, mappedBy = "resources")
	public Set<Permissions> getPermissionses() {
		return this.permissionses;
	}

	public void setPermissionses(Set<Permissions> permissionses) {
		this.permissionses = permissionses;
	}

}
