package entity;
// default package
// Generated Dec 7, 2020 9:16:49 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolesPermissions generated by hbm2java
 */
@Entity
@Table(name = "roles_permissions")
public class RolesPermissions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8461580131998700973L;
	private int rolesPermissionsId;
	private Permissions permissions;
	private Roles roles;

	public RolesPermissions() {
	}

	public RolesPermissions(int rolesPermissionsId) {
		this.rolesPermissionsId = rolesPermissionsId;
	}

	public RolesPermissions(int rolesPermissionsId, Permissions permissions, Roles roles) {
		this.rolesPermissionsId = rolesPermissionsId;
		this.permissions = permissions;
		this.roles = roles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Roles_Permissions_ID", unique = true, nullable = false)
	public int getRolesPermissionsId() {
		return this.rolesPermissionsId;
	}

	public void setRolesPermissionsId(int rolesPermissionsId) {
		this.rolesPermissionsId = rolesPermissionsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Permission_ID")
	public Permissions getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Permissions permissions) {
		this.permissions = permissions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Role_ID")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
