package entity;
// Generated Mar 9, 2019 2:17:56 AM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AerialActivities generated by hbm2java
 */
@Entity
@Table(name = "aerial_activities")
public class AerialActivities implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4081980226262103220L;
	private int aerialActivityId;
	private AerialPlans aerialPlans;
	private byte[] areaFile;
	private Date aerialActivityStartDate;
	private Date aerialActivityEndDate;

	private AerialActivityFlow aerialActivityFlow;

	@Embedded
	public AerialActivityFlow getAerialActivityFlow() {
		return aerialActivityFlow;
	}

	public void setAerialActivityFlow(AerialActivityFlow aerialActivityFlow) {
		this.aerialActivityFlow = aerialActivityFlow;
	}

	public AerialActivities() {
	}

	public AerialActivities(int aerialActivityId) {
		this.aerialActivityId = aerialActivityId;
	}
	
	private Set<RealMissions> realmissionses = new HashSet<RealMissions>(0);

	public AerialActivities(int aerialActivityId, AerialPlans aerialPlans, byte[] areaFile,
			Date aerialActivityStartDate, Date aerialActivityEndDate, AerialActivityFlow aerialActivityFlow,
			Set<RealMissions> realmissionses) {
		super();
		this.aerialActivityId = aerialActivityId;
		this.aerialPlans = aerialPlans;
		this.areaFile = areaFile;
		this.aerialActivityStartDate = aerialActivityStartDate;
		this.aerialActivityEndDate = aerialActivityEndDate;
		this.aerialActivityFlow = aerialActivityFlow;
		this.realmissionses = realmissionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Aerial_Activity_ID", unique = true, nullable = false)
	public int getAerialActivityId() {
		return this.aerialActivityId;
	}

	public void setAerialActivityId(int aerialActivityId) {
		this.aerialActivityId = aerialActivityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Aerial_Plan_ID")
	public AerialPlans getAerialPlans() {
		return this.aerialPlans;
	}

	public void setAerialPlans(AerialPlans aerialPlans) {
		this.aerialPlans = aerialPlans;
	}

	@Column(name = "Area_File")
	public byte[] getAreaFile() {
		return this.areaFile;
	}

	public void setAreaFile(byte[] areaFile) {
		this.areaFile = areaFile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Start_Date", length = 10)
	public Date getAerialActivityStartDate() {
		return aerialActivityStartDate;
	}

	public void setAerialActivityStartDate(Date aerialActivityStartDate) {
		this.aerialActivityStartDate = aerialActivityStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "End_Date", length = 10)
	public Date getAerialActivityEndDate() {
		return aerialActivityEndDate;
	}

	public void setAerialActivityEndDate(Date aerialActivityEndDate) {
		this.aerialActivityEndDate = aerialActivityEndDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aerialActivities")
	public Set<RealMissions> getRealmissionses() {
		return realmissionses;
	}

	public void setRealmissionses(Set<RealMissions> realmissionses) {
		this.realmissionses = realmissionses;
	}
}
