package entity;
// Generated 2019/5/19 ?? 06:34:20 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Missions generated by hbm2java
 */
@Entity
@Table(name = "missions")
public class Missions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1400236623216782400L;
	private Integer missionId;
	private AerialPlans aerialPlans;
	private Equipments equipments;
	private Persons persons;

	public Missions() {
	}

	public Missions(AerialPlans aerialPlans, Equipments equipments, Persons persons) {
		this.aerialPlans = aerialPlans;
		this.equipments = equipments;
		this.persons = persons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Mission_ID", unique = true, nullable = false)
	public Integer getMissionId() {
		return this.missionId;
	}

	public void setMissionId(Integer missionId) {
		this.missionId = missionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Aerial_Plan_ID")
	public AerialPlans getAerialPlans() {
		return this.aerialPlans;
	}

	public void setAerialPlans(AerialPlans aerialPlans) {
		this.aerialPlans = aerialPlans;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Equipment_ID")
	public Equipments getEquipments() {
		return this.equipments;
	}

	public void setEquipments(Equipments equipments) {
		this.equipments = equipments;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Person_ID")
	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

}
