package entity;
// Generated Mar 9, 2019 2:17:56 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OperationLimits generated by hbm2java
 */
@Entity
@Table(name = "operation_limits")
public class OperationLimits implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7746742909830702025L;
	private Integer operationLimitId;
	private String name;
	private Set<OperationlimitsLicenses> operationlimitsLicenseses = new HashSet<OperationlimitsLicenses>(0);
	private Set<OperationlimitsAerialplans> operationlimitsAerialplanses = new HashSet<OperationlimitsAerialplans>(0);

	public OperationLimits() {
	}

	public OperationLimits(String name, Set<OperationlimitsLicenses> operationlimitsLicenseses, Set<OperationlimitsAerialplans> operationlimitsAerialplanses) {
		this.name = name;
		this.operationlimitsLicenseses = operationlimitsLicenseses;
		this.operationlimitsAerialplanses = operationlimitsAerialplanses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Operation_Limit_ID", unique = true, nullable = false)
	public Integer getOperationLimitId() {
		return this.operationLimitId;
	}

	public void setOperationLimitId(Integer operationLimitId) {
		this.operationLimitId = operationLimitId;
	}

	@Column(name = "Name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operationLimits")
	public Set<OperationlimitsLicenses> getOperationlimitsLicenseses() {
		return this.operationlimitsLicenseses;
	}

	public void setOperationlimitsLicenseses(Set<OperationlimitsLicenses> operationlimitsLicenseses) {
		this.operationlimitsLicenseses = operationlimitsLicenseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operationLimits")
	public Set<OperationlimitsAerialplans> getOperationlimitsAerialplanses() {
		return this.operationlimitsAerialplanses;
	}

	public void setOperationlimitsAerialplanses(Set<OperationlimitsAerialplans> operationlimitsAerialplanses) {
		this.operationlimitsAerialplanses = operationlimitsAerialplanses;
	}

}
